export interface RwandaBusiness {
  name: string
  category: string
  district: string
  website?: string
  phone?: string
  description?: string
  verified: boolean
  verifiedSource: string
}

export const verifiedRwandanBusinesses: RwandaBusiness[] = [
  // ── Telecommunications ──
  { name: 'MTN Rwanda', category: 'Telecommunications', district: 'Kigali', website: 'https://mtn.co.rw', phone: '0790038006', verified: true, verifiedSource: 'rura.rw' },
  { name: 'Airtel Rwanda', category: 'Telecommunications', district: 'Kigali', website: 'https://africa.airtel.com/rwanda', verified: true, verifiedSource: 'rura.rw' },
  { name: 'RwandaTel', category: 'Telecommunications', district: 'Kigali', verified: true, verifiedSource: 'rura.rw' },
  { name: 'Liquid Telecom Rwanda', category: 'Telecommunications', district: 'Kigali', website: 'https://liquid.tech', verified: true, verifiedSource: 'rura.rw' },
  { name: 'RURA Rwanda', category: 'Government Services', district: 'Kigali', website: 'https://rura.rw', verified: true, verifiedSource: 'gov.rw' },

  // ── Banking & Finance ──
  { name: 'Bank of Kigali', category: 'Banking & Finance', district: 'Kigali', website: 'https://bk.rw', phone: '0788176000', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'Equity Bank Rwanda', category: 'Banking & Finance', district: 'Kigali', website: 'https://equitybankgroup.com', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'BPR Bank Rwanda', category: 'Banking & Finance', district: 'Kigali', website: 'https://bpr.rw', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'I&M Bank Rwanda', category: 'Banking & Finance', district: 'Kigali', website: 'https://imbank.com', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'Cogebanque', category: 'Banking & Finance', district: 'Kigali', website: 'https://cogebanque.co.rw', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'Access Bank Rwanda', category: 'Banking & Finance', district: 'Kigali', website: 'https://accessbankrwanda.com', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'GT Bank Rwanda', category: 'Banking & Finance', district: 'Kigali', website: 'https://gtbank.com', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'Urwego Bank', category: 'Banking & Finance', district: 'Kigali', website: 'https://urwegobank.com', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'Rwanda National Savings Bank', category: 'Banking & Finance', district: 'Kigali', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'Zigama CSS', category: 'Banking & Finance', district: 'Kigali', website: 'https://zigamacss.rw', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'Vision Fund Rwanda', category: 'Banking & Finance', district: 'Kigali', website: 'https://visionfund.org', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'Rwanda Microfinance Ltd', category: 'Banking & Finance', district: 'Kigali', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'Ecobank Rwanda', category: 'Banking & Finance', district: 'Kigali', website: 'https://ecobank.com', verified: true, verifiedSource: 'bnr.rw' },
  { name: 'National Bank of Rwanda', category: 'Banking & Finance', district: 'Kigali', website: 'https://bnr.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'MFI Inkunga Finance', category: 'Banking & Finance', district: 'Northern Province', verified: true, verifiedSource: 'bnr.rw' },

  // ── Government Services ──
  { name: 'Rwanda Revenue Authority', category: 'Government Services', district: 'Kigali', website: 'https://rra.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Irembo', category: 'Government Services', district: 'Kigali', website: 'https://irembo.gov.rw', description: 'Rwanda\'s national e-government services platform.', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Rwanda Development Board', category: 'Government Services', district: 'Kigali', website: 'https://rdb.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Rwanda Immigration', category: 'Government Services', district: 'Kigali', website: 'https://migration.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'City of Kigali', category: 'Government Services', district: 'Kigali', website: 'https://cityofkigali.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Rwanda National Police', category: 'Government Services', district: 'Kigali', website: 'https://police.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Rwanda Correctional Service', category: 'Government Services', district: 'Kigali', website: 'https://rcs.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Ministry of Finance Rwanda', category: 'Government Services', district: 'Kigali', website: 'https://minecofin.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Ministry of Health Rwanda', category: 'Government Services', district: 'Kigali', website: 'https://moh.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Rwanda Food and Drugs Authority', category: 'Government Services', district: 'Kigali', website: 'https://rfda.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'National Land Centre Rwanda', category: 'Government Services', district: 'Kigali', website: 'https://nlc.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Rwanda Social Security Board', category: 'Government Services', district: 'Kigali', website: 'https://rssb.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Public Procurement Authority Rwanda', category: 'Government Services', district: 'Kigali', website: 'https://rppa.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Rwanda Environment Management Authority', category: 'Government Services', district: 'Kigali', website: 'https://rema.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Gasabo District', category: 'Government Services', district: 'Kigali', website: 'https://gasabo.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Nyarugenge District', category: 'Government Services', district: 'Kigali', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Kicukiro District', category: 'Government Services', district: 'Kigali', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Musanze District', category: 'Government Services', district: 'Northern Province', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Huye District', category: 'Government Services', district: 'Southern Province', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Rubavu District', category: 'Government Services', district: 'Western Province', verified: true, verifiedSource: 'gov.rw' },

  // ── Healthcare ──
  { name: 'King Faisal Hospital', category: 'Healthcare', district: 'Kigali', website: 'https://kfh.rw', phone: '0788303222', description: 'Rwanda\'s largest referral hospital.', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'CHUK Hospital', category: 'Healthcare', district: 'Kigali', website: 'https://chuk.rw', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Baho International Hospital', category: 'Healthcare', district: 'Kigali', website: 'https://bahohospital.com', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Rwanda Biomedical Centre', category: 'Healthcare', district: 'Kigali', website: 'https://rbc.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Kibagabaga Hospital', category: 'Healthcare', district: 'Kigali', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Masaka Hospital', category: 'Healthcare', district: 'Kigali', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Muhima Hospital', category: 'Healthcare', district: 'Kigali', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Ruhengeri Hospital', category: 'Healthcare', district: 'Northern Province', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Butaro District Hospital', category: 'Healthcare', district: 'Northern Province', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Huye District Hospital', category: 'Healthcare', district: 'Southern Province', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Gitwe District Hospital', category: 'Healthcare', district: 'Southern Province', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Kibungo Hospital', category: 'Healthcare', district: 'Eastern Province', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Rwamagana Provincial Hospital', category: 'Healthcare', district: 'Eastern Province', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Kibuye Hospital', category: 'Healthcare', district: 'Western Province', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Kabgayi District Hospital', category: 'Healthcare', district: 'Southern Province', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Polyclinique Galien', category: 'Healthcare', district: 'Kigali', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Heal Africa Rwanda', category: 'Healthcare', district: 'Western Province', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Pharmacy Chez Lando', category: 'Healthcare', district: 'Kigali', verified: true, verifiedSource: 'rbc.gov.rw' },
  { name: 'Rwanda Medical Supply', category: 'Healthcare', district: 'Kigali', website: 'https://rms.rw', verified: true, verifiedSource: 'rbc.gov.rw' },

  // ── Airlines & Transport ──
  { name: 'RwandAir', category: 'Airlines & Transport', district: 'Kigali', website: 'https://rwandair.com', phone: '0788177000', description: 'Rwanda\'s national carrier airline.', verified: true, verifiedSource: 'caa.gov.rw' },
  { name: 'Kigali International Airport', category: 'Airlines & Transport', district: 'Kigali', website: 'https://rab.gov.rw', verified: true, verifiedSource: 'rab.gov.rw' },
  { name: 'Rwanda Airports Company', category: 'Airlines & Transport', district: 'Kigali', website: 'https://rab.gov.rw', verified: true, verifiedSource: 'rab.gov.rw' },
  { name: 'Rwanda Civil Aviation Authority', category: 'Airlines & Transport', district: 'Kigali', website: 'https://caa.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Horizon Express Rwanda', category: 'Airlines & Transport', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Trinity Express Rwanda', category: 'Airlines & Transport', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Volcano Express', category: 'Airlines & Transport', district: 'Northern Province', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Kigali Bus Services', category: 'Airlines & Transport', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Rwanda Transport Development Authority', category: 'Airlines & Transport', district: 'Kigali', website: 'https://rtda.gov.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Mwezi Express', category: 'Airlines & Transport', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Capital Express Rwanda', category: 'Airlines & Transport', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Rwanda National Road Agency', category: 'Airlines & Transport', district: 'Kigali', website: 'https://rnra.rw', verified: true, verifiedSource: 'gov.rw' },

  // ── Hospitality & Tourism ──
  { name: 'Kigali Marriott Hotel', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://marriott.com', phone: '0788185000', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Radisson Blu Kigali', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://radissonhotels.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Kigali Convention Centre', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://kcc.rw', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Serena Hotel Kigali', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://serenahotels.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Heaven Restaurant & Boutique Hotel', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://heavenrwanda.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Lemigo Hotel Kigali', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://lemigohotel.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Gorilla\'s Hotel Kigali', category: 'Hospitality & Tourism', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Hotel des Mille Collines', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://millecollines.net', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Park Inn by Radisson Kigali', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://radissonhotels.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Retreat Kigali', category: 'Hospitality & Tourism', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Ubumwe Grande Hotel', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://ubumwegrandehotel.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Mount Gorilla View Lodge', category: 'Hospitality & Tourism', district: 'Northern Province', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Bisate Lodge', category: 'Hospitality & Tourism', district: 'Northern Province', website: 'https://wilderness-safaris.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Sabyinyo Silverback Lodge', category: 'Hospitality & Tourism', district: 'Northern Province', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Five Volcanoes Boutique Hotel', category: 'Hospitality & Tourism', district: 'Northern Province', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Kivu Serena Hotel', category: 'Hospitality & Tourism', district: 'Western Province', website: 'https://serenahotels.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Inzu Lodge Musanze', category: 'Hospitality & Tourism', district: 'Northern Province', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Kigali Genocide Memorial', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://kgm.rw', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Rwanda Cultural Village', category: 'Hospitality & Tourism', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Inema Arts Center', category: 'Hospitality & Tourism', district: 'Kigali', website: 'https://inemaarts.com', verified: true, verifiedSource: 'rdb.rw' },

  // ── Retail & Shopping ──
  { name: 'Simba Supermarket', category: 'Retail & Shopping', district: 'Kigali', website: 'https://simba.rw', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Carrefour Kigali', category: 'Retail & Shopping', district: 'Kigali', website: 'https://carrefour.rw', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Nakumatt Kigali', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'UTC Kigali', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Kigali City Tower Mall', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Union Trade Centre', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Crystal Mall Kigali', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Nyamirambo Wholesale Market', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Kimironko Market', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Gikondo Market', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Kigali Special Economic Zone', category: 'Retail & Shopping', district: 'Kigali', website: 'https://ksez.rw', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Toyota Rwanda', category: 'Retail & Shopping', district: 'Kigali', website: 'https://toyotarwanda.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'CFAO Motors Rwanda', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Magerwa', category: 'Retail & Shopping', district: 'Kigali', website: 'https://magerwa.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Bourbon Coffee Rwanda', category: 'Retail & Shopping', district: 'Kigali', website: 'https://bourboncoffeerwanda.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Java House Rwanda', category: 'Retail & Shopping', district: 'Kigali', website: 'https://javahouseafrica.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Primus Brasseries', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Skol Brewery Rwanda', category: 'Retail & Shopping', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Inyange Industries', category: 'Retail & Shopping', district: 'Kigali', website: 'https://inyange.rw', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Ruhengeri Market', category: 'Retail & Shopping', district: 'Northern Province', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Nyanza Market', category: 'Retail & Shopping', district: 'Southern Province', verified: true, verifiedSource: 'rdb.rw' },

  // ── Education ──
  { name: 'University of Rwanda', category: 'Education', district: 'Kigali', website: 'https://ur.ac.rw', verified: true, verifiedSource: 'hec.gov.rw' },
  { name: 'Carnegie Mellon University Africa', category: 'Education', district: 'Kigali', website: 'https://africa.cmu.edu', verified: true, verifiedSource: 'hec.gov.rw' },
  { name: 'African Leadership University', category: 'Education', district: 'Kigali', website: 'https://alueducation.com', verified: true, verifiedSource: 'hec.gov.rw' },
  { name: 'University of Kigali', category: 'Education', district: 'Kigali', website: 'https://uok.ac.rw', verified: true, verifiedSource: 'hec.gov.rw' },
  { name: 'INES Ruhengeri', category: 'Education', district: 'Northern Province', website: 'https://ines.ac.rw', verified: true, verifiedSource: 'hec.gov.rw' },
  { name: 'Kigali Independent University', category: 'Education', district: 'Kigali', website: 'https://ulk.ac.rw', verified: true, verifiedSource: 'hec.gov.rw' },
  { name: 'Adventist University of Central Africa', category: 'Education', district: 'Kigali', website: 'https://auca.ac.rw', verified: true, verifiedSource: 'hec.gov.rw' },
  { name: 'Greens College Kigali', category: 'Education', district: 'Kigali', verified: true, verifiedSource: 'hec.gov.rw' },
  { name: 'Riviera High School', category: 'Education', district: 'Kigali', verified: true, verifiedSource: 'mineduc.gov.rw' },
  { name: 'Ecole Belge de Kigali', category: 'Education', district: 'Kigali', verified: true, verifiedSource: 'mineduc.gov.rw' },
  { name: 'Green Hills Academy', category: 'Education', district: 'Kigali', website: 'https://greenhillsacademy.rw', verified: true, verifiedSource: 'mineduc.gov.rw' },
  { name: 'Kigali International School', category: 'Education', district: 'Kigali', website: 'https://kis.ac.rw', verified: true, verifiedSource: 'mineduc.gov.rw' },
  { name: 'Rwanda Coding Academy', category: 'Education', district: 'Eastern Province', website: 'https://rca.ac.rw', verified: true, verifiedSource: 'mineduc.gov.rw' },
  { name: 'Rwanda Polytechnic', category: 'Education', district: 'Kigali', website: 'https://rp.ac.rw', verified: true, verifiedSource: 'hec.gov.rw' },

  // ── Energy & Utilities ──
  { name: 'REG Rwanda Energy Group', category: 'Energy & Utilities', district: 'Kigali', website: 'https://reg.rw', phone: '3939', verified: true, verifiedSource: 'gov.rw' },
  { name: 'WASAC', category: 'Energy & Utilities', district: 'Kigali', website: 'https://wasac.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'EDCL Rwanda', category: 'Energy & Utilities', district: 'Kigali', website: 'https://edcl.reg.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Gigawatt Global Rwanda', category: 'Energy & Utilities', district: 'Eastern Province', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Kivuwatt', category: 'Energy & Utilities', district: 'Western Province', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Total Energies Rwanda', category: 'Energy & Utilities', district: 'Kigali', website: 'https://totalenergies.rw', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Rubis Energy Rwanda', category: 'Energy & Utilities', district: 'Kigali', website: 'https://rubisenergy.com', verified: true, verifiedSource: 'rdb.rw' },
  { name: 'Engen Rwanda', category: 'Energy & Utilities', district: 'Kigali', verified: true, verifiedSource: 'rdb.rw' },

  // ── NGOs & Development ──
  { name: 'One Acre Fund Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://oneacrefund.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'World Vision Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://wvi.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'Imbuto Foundation', category: 'NGOs & Development', district: 'Kigali', website: 'https://imbutofoundation.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'SOS Children\'s Villages Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://sos-rwanda.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'CARE International Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://care.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'UNICEF Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://unicef.org/rwanda', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'UNDP Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://rw.undp.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'World Bank Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://worldbank.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'Concern Worldwide Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://concern.net', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'Oxfam Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://oxfam.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'Partners in Health Rwanda', category: 'NGOs & Development', district: 'Northern Province', website: 'https://pih.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'Rwanda Governance Board', category: 'NGOs & Development', district: 'Kigali', website: 'https://rgb.rw', verified: true, verifiedSource: 'gov.rw' },
  { name: 'Never Again Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://neveragainrwanda.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'Transparency International Rwanda', category: 'NGOs & Development', district: 'Kigali', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'African Development Bank Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://afdb.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'IMF Rwanda Office', category: 'NGOs & Development', district: 'Kigali', website: 'https://imf.org', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'GIZ Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://giz.de', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'Enabel Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://enabel.be', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'USAID Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://usaid.gov/rwanda', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'Rwanda Women\'s Network', category: 'NGOs & Development', district: 'Kigali', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'Inkomoko', category: 'NGOs & Development', district: 'Kigali', website: 'https://inkomoko.com', verified: true, verifiedSource: 'rgb.rw' },
  { name: 'UNHCR Rwanda', category: 'NGOs & Development', district: 'Kigali', website: 'https://unhcr.org/rwanda', verified: true, verifiedSource: 'rgb.rw' },
]
